// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTZr5wpVBIA1eKpLiue8sJZq4x7O-7vEI',
    appId: '1:1004506178454:web:6327aea6f525fa5a5333b7',
    messagingSenderId: '1004506178454',
    projectId: 'laundry-link-30f3a',
    authDomain: 'laundry-link-30f3a.firebaseapp.com',
    storageBucket: 'laundry-link-30f3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRz21wZ_Ky-SMRpBFT59-1GCdWR68GQHY',
    appId: '1:1004506178454:android:22e9893882b67c895333b7',
    messagingSenderId: '1004506178454',
    projectId: 'laundry-link-30f3a',
    storageBucket: 'laundry-link-30f3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuMzisYaJTP6NBg_1bip2v2rBTjZ8QHKs',
    appId: '1:1004506178454:ios:627d9c8f8db8b4625333b7',
    messagingSenderId: '1004506178454',
    projectId: 'laundry-link-30f3a',
    storageBucket: 'laundry-link-30f3a.firebasestorage.app',
    iosBundleId: 'com.example.laundryLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuMzisYaJTP6NBg_1bip2v2rBTjZ8QHKs',
    appId: '1:1004506178454:ios:627d9c8f8db8b4625333b7',
    messagingSenderId: '1004506178454',
    projectId: 'laundry-link-30f3a',
    storageBucket: 'laundry-link-30f3a.firebasestorage.app',
    iosBundleId: 'com.example.laundryLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTZr5wpVBIA1eKpLiue8sJZq4x7O-7vEI',
    appId: '1:1004506178454:web:fcf51cb6902395a35333b7',
    messagingSenderId: '1004506178454',
    projectId: 'laundry-link-30f3a',
    authDomain: 'laundry-link-30f3a.firebaseapp.com',
    storageBucket: 'laundry-link-30f3a.firebasestorage.app',
  );
}
